/**
 * Curated sample palettes — SINGLE preset source for every surface.
 *
 * Previously split: 8 operator presets here + 13 SaaS presets inline in
 * `apps/saas/src/app/dashboard/settings/theme-colors/page.tsx`. Phase 01
 * consolidates into this file. SaaS MUST import from here; do not duplicate.
 *
 * Shape matches `PlatformThemePayload` without importing `index` (avoids circular
 * exports). Compatibility IDs preserved — never rename an `id` without aliasing.
 */

export interface PlatformThemePreset {
  id: string;
  label: string;
  theme: { light: Record<string, string>; dark: Record<string, string> };
}

export const PLATFORM_THEME_PRESETS: readonly PlatformThemePreset[] = [
  // ── Original operator / App Builder presets (8) ──────────────────────────
  {
    id: "ocean",
    label: "Ocean",
    theme: {
      light: {
        primary: "#0369a1",
        primaryForeground: "#ffffff",
        secondary: "#f1f5f9",
        secondaryForeground: "#0f172a",
        accent: "#e0f2fe",
        accentForeground: "#0c4a6e",
        background: "#f8fafc",
        foreground: "#0f172a",
        muted: "#f1f5f9",
        mutedForeground: "#64748b",
        destructive: "#dc2626",
        card: "#ffffff",
        cardForeground: "#0f172a",
        border: "#e2e8f0",
      },
      dark: {
        primary: "#38bdf8",
        primaryForeground: "#0f172a",
        secondary: "#1e293b",
        secondaryForeground: "#f8fafc",
        accent: "#0c4a6e",
        accentForeground: "#e0f2fe",
        background: "#0f172a",
        foreground: "#f8fafc",
        muted: "#1e293b",
        mutedForeground: "#94a3b8",
        destructive: "#f87171",
        card: "#1e293b",
        cardForeground: "#f8fafc",
        border: "#334155",
      },
    },
  },
  {
    id: "forest",
    label: "Forest",
    theme: {
      light: {
        primary: "#166534",
        primaryForeground: "#ffffff",
        secondary: "#ecfdf5",
        secondaryForeground: "#14532d",
        accent: "#d1fae5",
        accentForeground: "#14532d",
        background: "#fafaf9",
        foreground: "#1c1917",
        muted: "#f5f5f4",
        mutedForeground: "#78716c",
        destructive: "#b91c1c",
        card: "#ffffff",
        cardForeground: "#1c1917",
        border: "#e7e5e4",
      },
      dark: {
        primary: "#4ade80",
        primaryForeground: "#052e16",
        secondary: "#14532d",
        secondaryForeground: "#ecfdf5",
        accent: "#166534",
        accentForeground: "#dcfce7",
        background: "#0c0a09",
        foreground: "#fafaf9",
        muted: "#292524",
        mutedForeground: "#a8a29e",
        destructive: "#fca5a5",
        card: "#1c1917",
        cardForeground: "#fafaf9",
        border: "#44403c",
      },
    },
  },
  {
    id: "sunset",
    label: "Sunset",
    theme: {
      light: {
        primary: "#ea580c",
        primaryForeground: "#ffffff",
        secondary: "#fff7ed",
        secondaryForeground: "#431407",
        accent: "#ffedd5",
        accentForeground: "#9a3412",
        background: "#fffbeb",
        foreground: "#1c1917",
        muted: "#fef3c7",
        mutedForeground: "#78716c",
        destructive: "#dc2626",
        card: "#ffffff",
        cardForeground: "#1c1917",
        border: "#fde68a",
      },
      dark: {
        primary: "#fb923c",
        primaryForeground: "#431407",
        secondary: "#431407",
        secondaryForeground: "#fff7ed",
        accent: "#9a3412",
        accentForeground: "#ffedd5",
        background: "#1c1917",
        foreground: "#fafaf9",
        muted: "#292524",
        mutedForeground: "#a8a29e",
        destructive: "#f87171",
        card: "#292524",
        cardForeground: "#fafaf9",
        border: "#57534e",
      },
    },
  },
  {
    id: "lavender",
    label: "Lavender",
    theme: {
      light: {
        primary: "#7c3aed",
        primaryForeground: "#ffffff",
        secondary: "#f5f3ff",
        secondaryForeground: "#4c1d95",
        accent: "#ede9fe",
        accentForeground: "#5b21b6",
        background: "#faf5ff",
        foreground: "#1e1b4b",
        muted: "#f3e8ff",
        mutedForeground: "#6b7280",
        destructive: "#dc2626",
        card: "#ffffff",
        cardForeground: "#1e1b4b",
        border: "#e9d5ff",
      },
      dark: {
        primary: "#a78bfa",
        primaryForeground: "#1e1b4b",
        secondary: "#4c1d95",
        secondaryForeground: "#f5f3ff",
        accent: "#5b21b6",
        accentForeground: "#ede9fe",
        background: "#1e1b4b",
        foreground: "#faf5ff",
        muted: "#312e81",
        mutedForeground: "#c4b5fd",
        destructive: "#f87171",
        card: "#312e81",
        cardForeground: "#faf5ff",
        border: "#4c1d95",
      },
    },
  },
  {
    id: "berry",
    label: "Berry",
    theme: {
      light: {
        primary: "#be123c",
        primaryForeground: "#ffffff",
        secondary: "#fff1f2",
        secondaryForeground: "#881337",
        accent: "#ffe4e6",
        accentForeground: "#9f1239",
        background: "#fffafb",
        foreground: "#1c1917",
        muted: "#fce7f3",
        mutedForeground: "#78716c",
        destructive: "#b91c1c",
        card: "#ffffff",
        cardForeground: "#1c1917",
        border: "#fecdd3",
      },
      dark: {
        primary: "#fb7185",
        primaryForeground: "#450a0a",
        secondary: "#881337",
        secondaryForeground: "#fff1f2",
        accent: "#9f1239",
        accentForeground: "#ffe4e6",
        background: "#0c0a09",
        foreground: "#fafaf9",
        muted: "#292524",
        mutedForeground: "#d6d3d1",
        destructive: "#fca5a5",
        card: "#1c1917",
        cardForeground: "#fafaf9",
        border: "#44403c",
      },
    },
  },
  {
    id: "amber",
    label: "Amber",
    theme: {
      light: {
        primary: "#d97706",
        primaryForeground: "#ffffff",
        secondary: "#fffbeb",
        secondaryForeground: "#78350f",
        accent: "#fef3c7",
        accentForeground: "#92400e",
        background: "#fffbeb",
        foreground: "#1c1917",
        muted: "#fef9c3",
        mutedForeground: "#78716c",
        destructive: "#dc2626",
        card: "#ffffff",
        cardForeground: "#1c1917",
        border: "#fde68a",
      },
      dark: {
        primary: "#fbbf24",
        primaryForeground: "#422006",
        secondary: "#78350f",
        secondaryForeground: "#fffbeb",
        accent: "#92400e",
        accentForeground: "#fef3c7",
        background: "#1c1917",
        foreground: "#fafaf9",
        muted: "#292524",
        mutedForeground: "#a8a29e",
        destructive: "#f87171",
        card: "#292524",
        cardForeground: "#fafaf9",
        border: "#57534e",
      },
    },
  },
  {
    id: "fuchsia",
    label: "Fuchsia",
    theme: {
      light: {
        primary: "#c026d3",
        primaryForeground: "#ffffff",
        secondary: "#fdf4ff",
        secondaryForeground: "#86198f",
        accent: "#fae8ff",
        accentForeground: "#a21caf",
        background: "#fafafa",
        foreground: "#18181b",
        muted: "#f4f4f5",
        mutedForeground: "#71717a",
        destructive: "#dc2626",
        card: "#ffffff",
        cardForeground: "#18181b",
        border: "#f0abfc",
      },
      dark: {
        primary: "#e879f9",
        primaryForeground: "#4a044e",
        secondary: "#86198f",
        secondaryForeground: "#fdf4ff",
        accent: "#a21caf",
        accentForeground: "#fae8ff",
        background: "#18181b",
        foreground: "#fafafa",
        muted: "#27272a",
        mutedForeground: "#a1a1aa",
        destructive: "#f87171",
        card: "#27272a",
        cardForeground: "#fafafa",
        border: "#a21caf",
      },
    },
  },
  {
    id: "ruby",
    label: "Ruby",
    theme: {
      light: {
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#fef2f2",
        secondaryForeground: "#7f1d1d",
        accent: "#fecaca",
        accentForeground: "#991b1b",
        background: "#fffafa",
        foreground: "#450a0a",
        muted: "#fee2e2",
        mutedForeground: "#b91c1c",
        destructive: "#991b1b",
        card: "#ffffff",
        cardForeground: "#450a0a",
        border: "#fecaca",
      },
      dark: {
        primary: "#f87171",
        primaryForeground: "#450a0a",
        secondary: "#7f1d1d",
        secondaryForeground: "#fef2f2",
        accent: "#991b1b",
        accentForeground: "#fecaca",
        background: "#0c0a09",
        foreground: "#fef2f2",
        muted: "#450a0a",
        mutedForeground: "#fca5a5",
        destructive: "#fca5a5",
        card: "#1c1917",
        cardForeground: "#fef2f2",
        border: "#7f1d1d",
      },
    },
  },
  // ── SaaS tenant-dashboard presets (13) — migrated here in Phase 01 ───────
  {
    id: "dilivygo-classic",
    label: "Dilivygo Classic",
    theme: {
      light: {
        primary: "#2563EB",
        primaryForeground: "#FFFFFF",
        secondary: "#F8FAFC",
        secondaryForeground: "#0F172A",
        accent: "#F1F5F9",
        accentForeground: "#0F172A",
        background: "#FFFFFF",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E2E8F0",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#3B82F6",
        primaryForeground: "#0B0B0C",
        secondary: "#111827",
        secondaryForeground: "#F8FAFC",
        accent: "#1F2937",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#111827",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#1F2937",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "emerald-mint",
    label: "Emerald Mint",
    theme: {
      light: {
        primary: "#10B981",
        primaryForeground: "#052E2B",
        secondary: "#F8FAFC",
        secondaryForeground: "#0F172A",
        accent: "#ECFDF5",
        accentForeground: "#064E3B",
        background: "#FFFFFF",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E2E8F0",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#34D399",
        primaryForeground: "#052E2B",
        secondary: "#0B1220",
        secondaryForeground: "#ECFDF5",
        accent: "#0F1A2B",
        accentForeground: "#ECFDF5",
        background: "#0B0B0C",
        foreground: "#ECFDF5",
        card: "#0B1220",
        cardForeground: "#ECFDF5",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#1F2937",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "violet-noir",
    label: "Violet Noir",
    theme: {
      light: {
        primary: "#7C3AED",
        primaryForeground: "#FFFFFF",
        secondary: "#FAFAFF",
        secondaryForeground: "#111827",
        accent: "#F3E8FF",
        accentForeground: "#3B0764",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#A78BFA",
        primaryForeground: "#0B0B0C",
        secondary: "#171328",
        secondaryForeground: "#F8FAFC",
        accent: "#221B3A",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#171328",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#2A2446",
        destructive: "#FB7185",
      },
    },
  },
  {
    id: "sunset-amber",
    label: "Sunset Amber",
    theme: {
      light: {
        primary: "#F59E0B",
        primaryForeground: "#1F2937",
        secondary: "#FFFBEB",
        secondaryForeground: "#1F2937",
        accent: "#FEF3C7",
        accentForeground: "#92400E",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F9FAFB",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#FBBF24",
        primaryForeground: "#0B0B0C",
        secondary: "#1C1408",
        secondaryForeground: "#F8FAFC",
        accent: "#2A1D0A",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#1C1408",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#3B2A13",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "rose-quartz",
    label: "Rose Quartz",
    theme: {
      light: {
        primary: "#E11D48",
        primaryForeground: "#FFFFFF",
        secondary: "#FFF1F2",
        secondaryForeground: "#111827",
        accent: "#FFE4E6",
        accentForeground: "#9F1239",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F9FAFB",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#FB7185",
        primaryForeground: "#0B0B0C",
        secondary: "#231017",
        secondaryForeground: "#F8FAFC",
        accent: "#2E141C",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#231017",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#3A1B25",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "graphite-mono",
    label: "Graphite Mono",
    theme: {
      light: {
        primary: "#111827",
        primaryForeground: "#FFFFFF",
        secondary: "#F3F4F6",
        secondaryForeground: "#111827",
        accent: "#E5E7EB",
        accentForeground: "#111827",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F3F4F6",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#E5E7EB",
        primaryForeground: "#0B0B0C",
        secondary: "#111827",
        secondaryForeground: "#F8FAFC",
        accent: "#1F2937",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#111827",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#1F2937",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "ocean-depths",
    label: "Ocean Depths",
    theme: {
      light: {
        primary: "#0EA5E9",
        primaryForeground: "#082F49",
        secondary: "#F0F9FF",
        secondaryForeground: "#0F172A",
        accent: "#E0F2FE",
        accentForeground: "#0C4A6E",
        background: "#FFFFFF",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E2E8F0",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#38BDF8",
        primaryForeground: "#082F49",
        secondary: "#071827",
        secondaryForeground: "#E0F2FE",
        accent: "#0B2234",
        accentForeground: "#E0F2FE",
        background: "#0B0B0C",
        foreground: "#E0F2FE",
        card: "#071827",
        cardForeground: "#E0F2FE",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#123047",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "teal-slate",
    label: "Teal Slate",
    theme: {
      light: {
        primary: "#14B8A6",
        primaryForeground: "#042F2E",
        secondary: "#F8FAFC",
        secondaryForeground: "#0F172A",
        accent: "#CCFBF1",
        accentForeground: "#134E4A",
        background: "#FFFFFF",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E2E8F0",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#2DD4BF",
        primaryForeground: "#042F2E",
        secondary: "#0B1220",
        secondaryForeground: "#F0FDFA",
        accent: "#0F1D2B",
        accentForeground: "#F0FDFA",
        background: "#0B0B0C",
        foreground: "#F0FDFA",
        card: "#0B1220",
        cardForeground: "#F0FDFA",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#1F2937",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "indigo-ice",
    label: "Indigo Ice",
    theme: {
      light: {
        primary: "#4F46E5",
        primaryForeground: "#FFFFFF",
        secondary: "#EEF2FF",
        secondaryForeground: "#111827",
        accent: "#E0E7FF",
        accentForeground: "#312E81",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#818CF8",
        primaryForeground: "#0B0B0C",
        secondary: "#141432",
        secondaryForeground: "#F8FAFC",
        accent: "#1B1B3F",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#141432",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#2A2A57",
        destructive: "#FB7185",
      },
    },
  },
  {
    id: "copper-clay",
    label: "Copper Clay",
    theme: {
      light: {
        primary: "#C2410C",
        primaryForeground: "#FFFFFF",
        secondary: "#FFF7ED",
        secondaryForeground: "#1F2937",
        accent: "#FFEDD5",
        accentForeground: "#7C2D12",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F9FAFB",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#DC2626",
      },
      dark: {
        primary: "#FB923C",
        primaryForeground: "#0B0B0C",
        secondary: "#1C1208",
        secondaryForeground: "#F8FAFC",
        accent: "#291A0C",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#1C1208",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#3B2413",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "citrus-punch",
    label: "Citrus Punch",
    theme: {
      light: {
        primary: "#84CC16",
        primaryForeground: "#1A2E05",
        secondary: "#F7FEE7",
        secondaryForeground: "#111827",
        accent: "#ECFCCB",
        accentForeground: "#365314",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F9FAFB",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#A3E635",
        primaryForeground: "#1A2E05",
        secondary: "#0E1A0A",
        secondaryForeground: "#F7FEE7",
        accent: "#14240D",
        accentForeground: "#F7FEE7",
        background: "#0B0B0C",
        foreground: "#F7FEE7",
        card: "#0E1A0A",
        cardForeground: "#F7FEE7",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#273A1A",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "nord-frost",
    label: "Nord Frost",
    theme: {
      light: {
        primary: "#0F766E",
        primaryForeground: "#FFFFFF",
        secondary: "#F8FAFC",
        secondaryForeground: "#0F172A",
        accent: "#E2E8F0",
        accentForeground: "#0F172A",
        background: "#FCFCFD",
        foreground: "#0F172A",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#475569",
        border: "#E2E8F0",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#5EEAD4",
        primaryForeground: "#0B0B0C",
        secondary: "#0B1220",
        secondaryForeground: "#E2E8F0",
        accent: "#101C2C",
        accentForeground: "#E2E8F0",
        background: "#0B0B0C",
        foreground: "#E2E8F0",
        card: "#0B1220",
        cardForeground: "#E2E8F0",
        muted: "#0F172A",
        mutedForeground: "#94A3B8",
        border: "#1F2937",
        destructive: "#F87171",
      },
    },
  },
  {
    id: "sakura-night",
    label: "Sakura Night",
    theme: {
      light: {
        primary: "#DB2777",
        primaryForeground: "#FFFFFF",
        secondary: "#FDF2F8",
        secondaryForeground: "#111827",
        accent: "#FCE7F3",
        accentForeground: "#831843",
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#FFFFFF",
        cardForeground: "#111827",
        muted: "#F9FAFB",
        mutedForeground: "#4B5563",
        border: "#E5E7EB",
        destructive: "#EF4444",
      },
      dark: {
        primary: "#F472B6",
        primaryForeground: "#0B0B0C",
        secondary: "#22101B",
        secondaryForeground: "#F8FAFC",
        accent: "#2B1522",
        accentForeground: "#F8FAFC",
        background: "#0B0B0C",
        foreground: "#F8FAFC",
        card: "#22101B",
        cardForeground: "#F8FAFC",
        muted: "#0F172A",
        mutedForeground: "#A1A1AA",
        border: "#3A1B2E",
        destructive: "#F87171",
      },
    },
  },
] as const;

/** Compatibility check — all IDs must be unique. */
export const PLATFORM_THEME_PRESET_IDS: readonly string[] = PLATFORM_THEME_PRESETS.map((p) => p.id);
